---
title: Ken Booth
timezone: America/Chicago
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
theme: jekyll-theme-cayman
author: Ken Booth
description: About
baseurl: "/"
url: https://kenbooth.github.io
lang: en
exclude:
- README.md
- CHANGELOG.md
google_analytics: 
paginate: 5
