---
title: Ken Booth
timezone: America/Chicago
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
theme: jekyll-theme-cayman
author: Ken Booth
description: About
baseurl: ''
permalink: "/:title:output_ext"
url: https://kenbooth.net
lang: en
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji
exclude:
- README.md
- Gemfile
- Gemfile.lock
- CHANGELOG.md
google_analytics:
paginate: 5
paginate_path: "./page:num/"
