---
title: Ken Booth
timezone: America/Chicago
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
theme: jekyll-theme-cayman
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji
exclude:
- README.md
- Gemfile
- Gemfile.lock
- CHANGELOG.md
author: Ken Booth
description: About
baseurl: ''
url: https://kenbooth.net
permalink: /:title:output_ext
lang: en
google_analytics:
paginate: 5
paginate_path: "/page:num"
