title: Bit Reader
theme: jekyll-theme-cayman
author: Ken Booth
description: Daily Miscellany
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://kenbooth.github.io" # the base hostname & protocol for your site, e.g. http://example.com
lang: en
timezone: America/Chicago
exclude:
 - README.md
 - CHANGELOG.md
google_analytics:
paginate: 5
